TutProject/Models/TakeСredit.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TutProject.Models
{
    public class TakeСredit
    {
        public double Money { get; set; }

        public double Time { get; set; }

        public double Prc { get; set; }
        public int t { get; private set; }

        public string[] get_head()
        {
            string[] arr_str = { "№", "Дата платежа", "Сумма платежа", "Основной долг", "Проценты", "Остаток долга" };
            return arr_str;
        }


        public string[,] get_body()
        {
            double x, y;

            //DateTime date1 = new DateTime();
           // DateTime date1 = DateTime.Now.AddMonths(i).to
            y = (double)Prc / 100 / 12;
            x = (double)Money * (y + (y / ((double)Math.Pow(1 + y, (double)Time) - 1)));
            x = Math.Round(x);
            t = (int)Math.Round(Time);
            
            string[,] arr_table_row = new string[t, 6];
            
            for (int i = 0; i < t; i++)
            {
                Prc *= y;
                Money -= (x - Math.Round(Money * y));
                //teloCredita = (double)(x - Prc);
                arr_table_row[i, 0] = (i + 1).ToString();
                arr_table_row[i, 1] = DateTime.Now.AddMonths(i).ToLongDateString().ToString();
                arr_table_row[i, 2] = x.ToString();
                arr_table_row[i, 3] = Math.Round(x - Money * y).ToString();
                arr_table_row[i, 4] = Math.Round(Money * y).ToString();
                arr_table_row[i, 5] = Money.ToString();


            }

            return arr_table_row;
        }
/*        public int[,] get_body() 
        {

            int[,] mas = { { 1, 2, 3, 4, 5 , 6 }, { 1, 2, 3, 4, 5, 6 }, { 1, 2, 3, 4, 5, 6 }, { 1, 2, 3, 4, 5, 6 }};

            return mas;
        }*/

    }
}

TutProject/Controllers/CreditController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TutProject.Models;

namespace TutProject.Models
{
    public class CreditController : Controller
    {
        // GET: Credit
        public ActionResult Index()
        {
            return View(new TakeСredit());
        }

       [HttpPost]

        public ActionResult Contact(TakeСredit puk, string btn1)
        {
            if (btn1 == "btn1") 
            {
                
            }

            return View(puk);
        }

    }
}

TutProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TutProject.Models;

namespace TutProject.Controllers
{
    
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Contact()
        {

            return View();
        }
    }
}

TutProject/Views/Credit/Contact.cshtml
@model TutProject.Models.TakeСredit

@{
    ViewBag.Title = "Index";
}
@{ var cellCount = 0; }
<table class="table">
    <tr>
    @foreach (string item in Model.get_head())
    {
        <th>
            @item
        </th>
    }
    </tr>
    @foreach (string item in Model.get_body())
    {
        if (cellCount % 6 == 0)
        {
            @:<tr>
            }
            <td>
                @item
            </td>

            cellCount++;

            if (cellCount % 6 == 0)
            {
            @:</tr>
        }
    }
</table>

TutProject/Views/Credit/Index.cshtml
@model TutProject.Models.TakeСredit
@{
    ViewBag.Title = "Home Page";
}
<html>
    <head>
    </head>
    <body>
        <div class="row">
            @using (Html.BeginForm("Contact", "Credit", FormMethod.Post))
            {
                <div class="col-md-4">
                </div>
                <div class="col-md-4">

                    <h2>Расчитай свой кредит!</h2>
                    <p>Калькулятор</p>
                    <label for="Money">Сумма займа</label>
                    <input type="number" min="1000" class="form-control" id="Money" name="Money" value="@Model.Money" />
                    <label for="Time">Срок займа</label>
                    <input type="number" min="1" class="form-control" id="Time" name="Time" value="@Model.Time" />
                    <label for="Prc">Ставка</label>
                    <input type="number" min="1" class="form-control" id="Prc" name="Prc" value="@Model.Prc" />
                    <br>

                    <button type="submit" class="btn btn-info" id="btn1" value="btn1" name="btn1">Рассчитать</button>

                </div>
                <div class="col-md-4">


                </div>

            }
        </div>
     </body>

</html>

TutProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Имя приложения", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Credit")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - мое приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>